project:
  type: website
  output-dir: docs
  post-render: "scripts/decktape.sh"
  render:
    - "*.qmd"
    - "!assignments/files/"
    - "!files/tutorials/"
  resources:
    - files/tutorials/ec306-r-template.qmd
    - files/tutorials/ec306lfs.csv
 

website:
  title: "EC306 - Wages and Employment"
  navbar:
    pinned: true
    background: "#9e32a8"
    left:
      - href: index.qmd
        text: Home
      - syllabus.qmd
      - text: "Content"
        file: content/index.qmd
      - text: "Assignments"
        file: assignments/index.qmd

  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      background: dark
      contents:
      
        - section: "Overview"
          contents:
            - content/index.qmd
        - section: "Course content"
          contents:
            - text: "1. Introduction to Labour Market Economics"
              file: content/ch01.qmd
            - text: "2. The Canadian Labour Market, Measurement, and Research"
              file: content/ch02.qmd
            - text: "3. Labour Supply"
              file: content/ch03.qmd
            - text: "4. Labour Supply and Income Support Programs"
              file: content/ch04.qmd
            - text: "5. Labour Supply and Social Insurance Programs"
              file: content/ch05.qmd
            - text: "Introduction to R and Quarto"
              file: content/introtor.qmd
            - text: "6. Labour Supply and Early Career Decisions"
              file: content/ch06.qmd
            - text: "7. Labour Supply and Later Career Decisions"
              file: content/ch07.qmd
            - text: "8. Labour Demand"
              file: content/ch08.qmd
            - text: "9. Labour Demand in Global Markets"
              file: content/ch09.qmd
            - text: "10. Labour Demand and Technology"
              file: content/ch10.qmd
            - text: "11. Competitive Labour Markets"
              file: content/ch11.qmd
            - text: "12. Imperfectly Competitive Labour Markets"
              file: content/ch12.qmd
            - text: "14. Human Capital Theory"
              file: content/ch14.qmd
            - text: "15. Wage Differentials Among Diverse Population Groups"
              file: content/ch15.qmd
              
    - title: "Assignments"
      style: "docked"
      search: false
      background: dark
      contents:
      
        - section: "Overview"
          contents:
            - assignments/index.qmd
        - section: "Assignments"
          contents:
            - text: "Assignment 1"
              file: assignments/assign1.qmd          
              
format:
  html:
    code-overflow: wrap
    theme: 
      - litera
      - html/custom.scss
    toc: true


